// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoUNIR9jALRx1cUp3BtsmtFq8_B7rCTZk',
    appId: '1:582411037437:web:52e515c56c3df3fe7bec94',
    messagingSenderId: '582411037437',
    projectId: 'my-note-a7a49',
    authDomain: 'my-note-a7a49.firebaseapp.com',
    storageBucket: 'my-note-a7a49.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGJUXJ22sGYjJ9bW-KckxcvkP2h-5eXiQ',
    appId: '1:582411037437:android:2b3436b9d433afea7bec94',
    messagingSenderId: '582411037437',
    projectId: 'my-note-a7a49',
    storageBucket: 'my-note-a7a49.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEgSSGdNUCQHBtlOIk5lY-ZgxM7BmrAFw',
    appId: '1:582411037437:ios:4c2c1e0f1f468fa87bec94',
    messagingSenderId: '582411037437',
    projectId: 'my-note-a7a49',
    storageBucket: 'my-note-a7a49.firebasestorage.app',
    iosBundleId: 'com.example.myNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEgSSGdNUCQHBtlOIk5lY-ZgxM7BmrAFw',
    appId: '1:582411037437:ios:4c2c1e0f1f468fa87bec94',
    messagingSenderId: '582411037437',
    projectId: 'my-note-a7a49',
    storageBucket: 'my-note-a7a49.firebasestorage.app',
    iosBundleId: 'com.example.myNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoUNIR9jALRx1cUp3BtsmtFq8_B7rCTZk',
    appId: '1:582411037437:web:0d7851282a37883e7bec94',
    messagingSenderId: '582411037437',
    projectId: 'my-note-a7a49',
    authDomain: 'my-note-a7a49.firebaseapp.com',
    storageBucket: 'my-note-a7a49.firebasestorage.app',
  );
}
